- forestry-club-hour-tracker/package-lock.json
- forestry-club-hour-tracker/package.json
- forestry-club-hour-tracker/src/AdminReview.jsx
- forestry-club-hour-tracker/src/App.jsx
- forestry-club-hour-tracker/src/Navigation.jsx
- forestry-club-hour-tracker/src/main.jsx
adds a simple routing table for the website to use.
> add routing table

- forestry-club-hour-tracker/index.html
- forestry-club-hour-tracker/package-lock.json
- forestry-club-hour-tracker/package.json
- forestry-club-hour-tracker/src/AdminReview.jsx
- forestry-club-hour-tracker/src/App.jsx
- forestry-club-hour-tracker/src/components/AdminNotify.jsx
* added bootstrap to index.html
* added react-bootstrap, bootstrap, prop-types to the node package
* create adminnotify component, which wraps data into a toast component for review
* Add accept/deny buttons, which should eventually close the toast and send a signal back of the action taken
* within AdminReview, create a dummy array that maps its elements to an AdminNotify component
> Add adminnotify component, react-bootstrap, proptypes

- forestry-club-hour-tracker/package.json
- forestry-club-hour-tracker/src/components/modify-hours/ModifyHours.jsx
- forestry-club-hour-tracker/src/components/modify-hours/calculation.js
- forestry-club-hour-tracker/src/components/modify-hours/modify-hours.css
- Full logging functionality for club members via dialog box
- Front-end validation and disallows future date/times
- Helper functions for formatting and converting date objects.
**Logging Hours Dialog Box:**
> Added Hour Logging Functionality

- .gitignore
- README.md
- docker-compose.yml
- scripts/README.md
- scripts/schema.sql
- create docker file
- create docker asset directory
- update readme with instructions
> Docker-SQL-schema

- forestry-club-hour-tracker/src/App.jsx
- forestry-club-hour-tracker/src/pages/Home.jsx
Refactor code for Home page into it's one page file.
> Home page.

- database/README.md
- database/database.js
- database/node_modules/.package-lock.json
- database/package-lock.json
- database/package.json
Simple connection file, can be lifted into your backend projects.
has sample data.
> add a db connection file.

- forestry-club-hour-tracker/src/components/Dropdown.jsx
- forestry-club-hour-tracker/src/pages/Home.jsx
Add drop down select component.
Call drop down select component on home page.
> Add Dropdown select component.

- forestry-club-hour-tracker/index.html
- forestry-club-hour-tracker/package.json
- forestry-club-hour-tracker/src/components/AddMember.jsx
- forestry-club-hour-tracker/src/main.jsx
- forestry-club-hour-tracker/src/pages/AdminClubView.jsx
- forestry-club-hour-tracker/src/server/server.js
- scripts/schema.sql
Add cors library for fetch requests. 
Connect AddMember.jsx to database. 
Connect AdminClubView.jsx to database. 
Move CSS link in index.html to remove browser console warnings.
Add script for starting api.
Add missing comma to schema.sql.
> Database connections P.1

- forestry-club-hour-tracker/src/App.jsx
- forestry-club-hour-tracker/src/router/AppRouter.jsx
Some code organization, this moves all the router logic to its own react component.
> Move react router from App to AppRouter

- forestry-club-hour-tracker/src/components/AddMember.jsx
- forestry-club-hour-tracker/src/components/modify-hours/ModifyHours.jsx
- forestry-club-hour-tracker/src/pages/AdminClubView.jsx
- forestry-club-hour-tracker/src/pages/AdminMemberView.jsx
- forestry-club-hour-tracker/src/pages/Home.jsx
- forestry-club-hour-tracker/src/server/controller/workhoursController.js
- forestry-club-hour-tracker/src/server/db/usersDB.js
- forestry-club-hour-tracker/src/server/db/workhoursDB.js
- forestry-club-hour-tracker/src/server/router/workhoursRouter.js
- scripts/testData.sql
Add testData.sql.
Add sql code to pull members hour totals.
Change clubview to reflect hours totals.
Connect AddMember.jsx to DB.
Connect AddHours component to database.
Connect AdminMemberView to database.
Remove most non-functional links.
> Database Connections P.2

- forestry-club-hour-tracker/package.json
- forestry-club-hour-tracker/src/pages/MemberHoursView.jsx
I have (hopefully) created a page that will show a member's name, along with their hours and the dates that they submitted their hours.
> Adding MemberHoursView.jsx page

- forestry-club-hour-tracker/package.json
- forestry-club-hour-tracker/src/components/MemberSelect.jsx
- forestry-club-hour-tracker/src/index.css
- forestry-club-hour-tracker/src/pages/Home.jsx
- forestry-club-hour-tracker/src/pages/MemberHoursView.jsx
- forestry-club-hour-tracker/src/router/AppRouter.jsx
- Created a new component that allows users to select a member from a dropdown, click a button, and navigate to a page to view their hours.
- Edited the MemberHoursView page to work with the implementation of the dropdown.
- Added a route to the AppRouter for the MemberViewHours page
- Added the new component to the Home page.
- Added some styling for the new component.
- Installed Axios and Concurrently.
> Navigation for members to view their hours. 

- forestry-club-hour-tracker/src/components/AddHours.jsx
- forestry-club-hour-tracker/src/components/DateTimePicker.jsx
Fix bug caused by timezone shifting when retrieving from database.
> Fix edit hours and add hours for timezones.

- forestry-club-hour-tracker/src/components/AdminNav.jsx
- forestry-club-hour-tracker/src/components/EditHours.jsx
- forestry-club-hour-tracker/src/components/Table.jsx
- forestry-club-hour-tracker/src/index.css
- forestry-club-hour-tracker/src/pages/AdminClubView.jsx
- forestry-club-hour-tracker/src/pages/AdminMemberView.jsx
- Edited table, button, and admin navigation styling. 
- Changed table sizing. 
- Added classes to elements in multiple files.
> Site styling for admin club view and admin member view

- forestry-club-hour-tracker/src/components/AddMember.jsx
- forestry-club-hour-tracker/src/components/AdminNav.jsx
- forestry-club-hour-tracker/src/components/Table.jsx
- forestry-club-hour-tracker/src/components/TableNav.jsx
- forestry-club-hour-tracker/src/index.css
- forestry-club-hour-tracker/src/pages/AdminClubView.jsx
- forestry-club-hour-tracker/src/pages/AdminMemberView.jsx
- forestry-club-hour-tracker/src/pages/MemberHoursView.jsx
- Changed the admin nav to a more reusable component called TableNav
- Moved some of the table styles to the Table component file
- Added some styling to the add member page
- Edited multiple views to include the updated TableNav
> Styling for all pages

- forestry-club-hour-tracker/src/App.jsx
- forestry-club-hour-tracker/src/api/hours.php
- forestry-club-hour-tracker/src/components/AdminNotify.jsx
- forestry-club-hour-tracker/src/pages/AdminClubView.jsx
- forestry-club-hour-tracker/src/pages/AdminReview.jsx
Fix AdminReview and AdminNotify to work with new api.
Add lines to api to work with AdminReview and AdminNotify.
Remove columns and rows from App.jsx.
> Fix AdminReview and AdminNotify to work with new api.

- forestry-club-hour-tracker/src/components/auth.jsx
- forestry-club-hour-tracker/src/config/firebase.jsx
- forestry-club-hour-tracker/src/pages/Login.jsx
- forestry-club-hour-tracker/src/router/AppRouter.jsx
Sign up using email and password is creating accounts in firebase, still working on logout
> Basic Auth using firebase

- forestry-club-hour-tracker/package.json
- forestry-club-hour-tracker/src/base_url.js
- forestry-club-hour-tracker/src/components/AddHours.jsx
- forestry-club-hour-tracker/src/components/AddMember.jsx
- forestry-club-hour-tracker/src/components/EditHours.jsx
- forestry-club-hour-tracker/src/components/MemberSelect.jsx
- forestry-club-hour-tracker/src/pages/AdminClubView.jsx
- forestry-club-hour-tracker/src/pages/AdminMemberView.jsx
- forestry-club-hour-tracker/src/pages/AdminReview.jsx
- forestry-club-hour-tracker/src/pages/MemberHoursView.jsx
Remove all instances of base url in code.
Create variable for base url to replace literal instances of it in code.
Add firebase to package.json.
Remove package.json scripts for server.js.
> Create variable for base url to replace literal instances of it in code.

- forestry-club-hour-tracker/src/App.css
- forestry-club-hour-tracker/src/pages/AdminMemberView.jsx
Adding active / inactive button to AdminMemberView page.
> Adding active/inactive button in AdminMemberView page

- README.md
- documentation/TROUBLESHOOTING.md
- package-lock.json
- Add documentation folder. 
- Add links to documentation in README.md. 
- Remove unused package-lock.json.
> First set of documentation changes.

- forestry-club-hour-tracker/src/helpers/translateData.js
- forestry-club-hour-tracker/src/hooks/useMemberHours.js
- forestry-club-hour-tracker/src/pages/AdminClubView.jsx
- forestry-club-hour-tracker/src/pages/AdminMemberView.jsx
- forestry-club-hour-tracker/src/pages/MemberHoursView.jsx
- forestry-club-hour-tracker/src/projectVariables.js
- forestry-club-hour-tracker/src/router/AppRouter.jsx
- Added loading to router to address flicker. 
- Extracted translate data functions to a helper file.
> Issue #49: Login page flickering when reloading on the homepage

- forestry-club-hour-tracker/src/components/MemberStatusControls.jsx
- forestry-club-hour-tracker/src/pages/AdminClubView.jsx
- forestry-club-hour-tracker/src/pages/AdminMemberView.jsx
Also removed the activity button from member view
> Implemented a switch to determine the activity status of members. 
